name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 18]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install

      - run: npm test

      - name: Save test output
        run: |
          mkdir -p test-reports
          npm test > test-reports/test-output.txt

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report-${{ matrix.node-version }}
          path: test-reports/test-output.txt
