name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 18]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test

      - name: Save test output
        run: |
          mkdir -p test-reports
          npm test > test-reports/test-output.txt

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report-${{ matrix.node-version }}
          path: test-reports/test-output.txt

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}:latest .

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}:latest

  integration-test:
    needs: build
    runs-on: ubuntu-latest

    services:
      app:
        image: ghcr.io/${{ github.repository }}:latest
        ports:
          - 3000:3000
        options: >-
          --health-cmd="curl -f http://localhost:3000 || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Wait for container to be ready
        run: sleep 10

      - name: Integration test: Home page should be reachable
        run: curl --fail http://localhost:3000 || exit 1
