name: Deploy to Render

on:
  workflow_run:
    workflows: ["Node.js CI"]   # <-- fixed workflow name here
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Ensure deploy hook is set
        run: |
          if [ -z "${{ secrets.RENDER_DEPLOY_HOOK_URL }}" ]; then
            echo "Missing RENDER_DEPLOY_HOOK_URL secret"; exit 1;
          fi

      - name: Trigger Render deploy
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
